# Generated by Django 3.2.7 on 2021-09-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuserform',
            name='Another_comment',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newuserform',
            name='Birthday',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='newuserform',
            name='District',
            field=models.CharField(choices=[('Dh', 'Dhaka'), ('kh', 'Khulna'), ('Jess', 'Jessore')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='newuserform',
            name='Radio',
            field=models.CharField(choices=[('Dh', 'Dhaka'), ('kh', 'Khulna'), ('Jess', 'Jessore')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='newuserform',
            name='captcha_answer',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='newuserform',
            name='cc_myself',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='newuserform',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='newuserform',
            name='name',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
