# Generated by Django 3.2.7 on 2021-09-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0003_auto_20210927_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuserform',
            name='comment',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='newuserform',
            name='username',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
