# Generated by Django 3.2.7 on 2021-09-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0004_auto_20210927_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuserform',
            name='Another_comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newuserform',
            name='Birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newuserform',
            name='Radio',
            field=models.CharField(blank=True, choices=[('', 'SELECT OPTIONS'), ('Dh', 'Dhaka'), ('kh', 'Khulna'), ('Jess', 'Jessore')], default='Dh', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='newuserform',
            name='captcha_answer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newuserform',
            name='cc_myself',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
